# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#allow
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  allow:
    - dependency-type: "production"
  open-pull-requests-limit: 5
  versioning-strategy: widen
  reviewers:
  - asmahood
